Update bufr to version 11.5.0 and ESMF to 8.1.1
NOAA-EMC/hpc-stack pull request #222
Opened 2021-04-26 15:37 UTC by kgerheiser

Will fix #208 and #214 once installed

2021-04-26 15:43 UTC, aerorahul approved these changes
LGTM

2021-04-26 20:24 UTC, aerorahul requested changes
we missed the install_as update for bufr.

2021-04-26 20:24 UTC, aerorahul commented on config/stack_custom.yaml
>    install_as: 11.4.0
@kgerheiser 
we missed this.
We want to also install as `11.5.0`

2021-04-26 20:24 UTC, aerorahul commented on config/stack_gaea.yaml
>    install_as: 11.4.0
and here

2021-04-26 20:24 UTC, aerorahul commented on config/stack_jedi.yaml
>    install_as: 11.4.0
here too

2021-04-26 20:24 UTC, aerorahul commented on config/stack_mac.yaml
>    install_as: 11.4.0
and everywhere

2021-04-26 20:24 UTC, aerorahul commented on config/stack_noaa.yaml
>    install_as: 11.4.0
too many yamls

2021-04-26 20:24 UTC, aerorahul commented on config/stack_ufs_weather_ci.yaml
>    install_as: 11.4.0
far too many.

2021-04-28 15:18 UTC, aerorahul approved these changes
looks good.

2021-04-28 16:04 UTC, merged

2021-04-28 17:07 UTC, junwang-noaa commented
@kgerheiser May I ask if the esmf 8.1.1 is now available on the supported platforms (dell, cray, hera, orion, jet)? Thanks

2021-04-28 17:19 UTC, kgerheiser commented
Building it now. @Hang-Lei-NOAA and @climbfuji can you install ESMF 8.1.1?

2021-04-28 17:27 UTC, Hang-Lei-NOAA commented
okay

On Wed, Apr 28, 2021 at 1:20 PM Kyle Gerheiser ***@***.***>
wrote:

> Building it now. @Hang-Lei-NOAA <https://github.com/Hang-Lei-NOAA> and
> @climbfuji <https://github.com/climbfuji> can you install ESMF 8.1.1?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/hpc-stack/pull/222#issuecomment-828633739>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKWSMFBNWVC6UZOX2OGQE7TTLA7URANCNFSM43TEJEIQ>
> .
>

2021-04-30 02:02 UTC, BinLiu-NOAA commented
Thanks @kgerheiser and @Hang-Lei-NOAA! I saw esmf/8_1_1 is now available on Hera, Orion, wcoss_cray, and wcoss_dell_p3. I could not find it on Jet yet. Could one of you help to build it on Jet as well when you get a chance? Much appreciated!

2021-05-03 12:42 UTC, junwang-noaa commented
@kgerheiser  May I ask if esmf811 is available on jet yet? We plan to update the model to use esmf811. Thanks.

2021-05-03 13:26 UTC, kgerheiser commented
Yes, sorry. I missed the debug install.

2021-05-03 14:54 UTC, kgerheiser commented
It's on Jet

2021-05-03 16:00 UTC, junwang-noaa commented
Thanks, Kyle!

On Mon, May 3, 2021 at 10:54 AM Kyle Gerheiser ***@***.***>
wrote:

> It's on Jet
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/hpc-stack/pull/222#issuecomment-831313490>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI7D6TJETTAFNT5DX5NEI5LTL22L5ANCNFSM43TEJEIQ>
> .
>