Add `csh` support for loading miniconda3
NOAA-EMC/hpc-stack pull request #377
Opened 2022-01-24 22:08 UTC by aerorahul

It was noted by @CoryMartin-NOAA that users of `csh` or `tcsh` got errors while loading the `miniconda3` module.
Upon further investigation, it was discovered that users of `csh` or `tcsh` need to source `conda.csh`.

This PR:
- adds support for `csh` based shells
- simplifies the loading process for `bash` leveraging LMod's built in capability of `source_sh`.  See the documentation of `source_sh` [here](https://lmod.readthedocs.io/en/latest/050_lua_modulefiles.html) for how it works.
- fixes a bug where new versions of miniconda are named with a prefix of python version it supports.

2022-01-24 22:45 UTC, climbfuji commented
This looks great, especially the `source_sh` feature. Have you tested if that works correctly when using `conda activate ...` and `conda deactivate` after loading the module and before unloading? What happens if the user forgets to do a `conda deactivate`?

Also, the documentation says:

> (New in version 8.6)
> This feature was introduced in Tmod 4.6 and was shamelessly studied and re-implemented in Lmod 8.6+.

Do all our systems support this?

2022-01-24 23:04 UTC, aerorahul commented
@climbfuji 
If a user did a `conda activate` and `conda deactivate` followed by unloading the module, then it works as expected.
If a user forgets to do a `conda deactivate` then module unload will simply `unset` the environment variables that were set during the loading.  It will not perform a `conda deactivate` as part of the "unsource-ing" (if you will).

May be I should try and see if I can perform a `conda deactivate` when unloading the modulefile, but that would mean a lot of the excessive stuff I removed.  It is particularly problematic for `csh`.  I can try in a later PR.

Since loading the module is not performing a `conda activate`, unloading is not performing a `conda deactivate`.
Those are command line executions deferred to the user at the moment.

I have no idea what the versions of LMod are on our systems at the moment.

2022-01-24 23:12 UTC, climbfuji commented
> @climbfuji If a user did a `conda activate` and `conda deactivate` followed by unloading the module, then it works as expected. If a user had performed a `conda activate` and forgets to do a `conda deactivate` prior to unloading the module, then `module unload `will simply `unset` the environment variables that were set during the loading. It will not perform a `conda deactivate` as part of the "unsource-ing" (if you will).
> 
> May be I should try and see if I can perform a `conda deactivate` when unloading the modulefile, but that would mean a lot of the excessive stuff I removed. It is particularly problematic for `csh`. I can try in a later PR.
> 
> Since loading the module is not performing a `conda activate`, therefore unloading is not performing a `conda deactivate`. Those are command line executions deferred to the user at the moment.
> 
> I have no idea what the versions of LMod are on our systems at the moment.

Ok, thanks, I was just curious. I can help collecting version informations for the various systems.

2022-01-24 23:29 UTC, climbfuji commented
There is an environment variable `LMOD_VERSION`.
```
# Orion
declare -x LMOD_VERSION="8.3.17"
# to be continued
...
```

2022-01-24 23:34 UTC, climbfuji requested changes, later dismissed
I really don't like pushing back, because the solution would have been great. But unless I got version numbers wrong none of the systems I looked at has a recent enough version of `lmod` to support the `source_sh` feature. Please double check to make sure I am correct.

2022-01-24 23:56 UTC, aerorahul commented
Totally understood.
In that case I need assistance in supporting the `csh` users.

2022-01-26 04:25 UTC, aerorahul commented
Ok @climbfuji 
Lets see if this passes the test.

2022-02-01 12:15 UTC, aerorahul commented
@climbfuji 
I have installed a test stack (for Miniconda) with this branch on Hera and  so that`csh`/`tcsh` volunteers could test the installation.

I provided the following instructions:
```
module use /scratch1/NCEPDEV/stmp4/Rahul.Mahajan/test_conda/modulefiles/stack
module load hpc/1.2.0

module load hpc-miniconda3/4.6.14

module load r2d2/1.0.0
module unload r2d2

conda activate
conda deactivate

module unload hpc-miniconda3
```

@CatherineThomas-NOAA is a `csh` user and verified that all steps completed without errors.

This PR has been tested with `csh` based shell users.  There is no change for `bash` users.

2022-02-01 13:53 UTC, climbfuji approved these changes

2022-02-01 13:58 UTC, merged