Feature/linux centos intel
NOAA-EMC/hpc-stack pull request #394
Opened 2022-02-24 15:07 UTC by natalie-perlin

2022-02-28 16:00 UTC, kgerheiser requested changes
Looks good. Could you just change the prefix overwrite block?

2022-02-28 16:00 UTC, kgerheiser commented on libs/build_libtiff.sh
> +                                   || ( echo "WARNING: $prefix EXISTS, SKIPPING"; exit 1 )
Could you change this to:

```
  if [[ -d $prefix ]]; then
      if [[ $OVERWRITE =~ [yYtT] ]]; then
          echo "WARNING: $prefix EXISTS: OVERWRITING!"
          $SUDO rm -rf $prefix
      else
          echo "WARNING: $prefix EXISTS, SKIPPING"
          exit 0
      fi
  fi
```

2022-02-28 22:25 UTC, natalie-perlin commented on libs/build_libtiff.sh
> +                                   || ( echo "WARNING: $prefix EXISTS, SKIPPING"; exit 1 )
updated build_libtiff.sh as requested

2022-03-01 19:21 UTC, kgerheiser approved these changes

2022-03-01 19:21 UTC, kgerheiser commented
@natalie-perlin could you update your branch. I'll merge this next.

2022-03-02 14:03 UTC, merged